name: Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn clean install
      working-directory: shape-calculator
    - name: Run tests with coverage
      run: mvn test jacoco:report
      working-directory: shape-calculator
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: shape-calculator/target/site/jacoco
    - name: Check coverage
      run: |
        echo "Coverage report generated:"
        cat shape-calculator/target/site/jacoco/index.html
